const dummyUser = [
  {
    id: 1,
    firstname: 'admin',
    lastname: 'admin',
    othername: 'admin',
    email: 'admin@questioner.com',
    phoneNumber: '08025137999',
    username: 'admin',
    password: 'admin',
    registered: new Date(),
    isAdmin: true,
  },
  {
    id: 2,
    firstname: 'Nedy',
    lastname: 'Udombat',
    othername: 'Edidiong',
    email: 'nedyudombat@gmail.com',
    phoneNumber: '08025137999',
    username: 'nedyy',
    password: 'qwertyuiop',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 3,
    firstname: 'Mfoniso',
    lastname: 'Atan',
    othername: 'Strota',
    email: 'mfonisoStrota@gmail.com',
    phoneNumber: '08034601726',
    username: 'strota',
    password: 'qwertyuiopasdfghjkl',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 4,
    firstname: 'Tresh',
    lastname: 'Ubon',
    othername: 'love',
    email: 'tresh@gmail.com',
    phoneNumber: '08030987726',
    username: 't-girl',
    password: 'zxcvbnmqwertyuiopasdfghjkl',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 5,
    firstname: 'Imobong',
    lastname: 'Udofot',
    othername: 'Aubrey',
    email: 'aubrey@gmail.com',
    phoneNumber: '08012345678',
    username: 'aubrey',
    password: 'qwertyuioqazsxwedcpasdfghjkl',
    registered: new Date(),
    isAdmin: false,
  },
  {
    id: 6,
    firstname: 'Teawhy',
    lastname: 'Yung',
    othername: 'Edwin',
    email: 'teawhy@gmail.com',
    phoneNumber: '07098765432',
    username: 'teawhy',
    password: 'quiopasdfghjkl',
    registered: new Date(),
    isAdmin: false,
  },
];

export default dummyUser;
