const dummyMeetup = [
  {
    id: 1,
    organizer: 'DevFest',
    topic: 'Web Accessibility',
    happeningOn: '3/4/2019',
    location: 'Uyo, Akwa Ibom State',
    Tags: ['Tech', 'Edu'],
    images: ['jpeg.png', 'nn.jpg'],
    createdOn: new Date(),
  },
  {
    id: 2,
    organizer: 'Dev C',
    topic: 'Developer Advocacy',
    happeningOn: '11/11/18',
    location: 'Civic Center, Lekki, Lagos',
    Tags: ['Tech', 'Social'],
    images: ['mark.png', 'neo.jpg'],
    createdOn: new Date(),
  },
  {
    id: 3,
    organizer: 'Dev Center',
    topic: 'Getting a Remote job',
    happeningOn: '2/12/20',
    location: 'Yaba, Lagos',
    Tags: ['Tech'],
    images: ['nedy.png', 'chamlice.jpg'],
    createdOn: new Date(),
  },
  {
    id: 4,
    organizer: 'Forloop',
    topic: 'The art of self care as a developer',
    happeningOn: '7/27/19',
    location: 'Gwagwalada, Abuja',
    Tags: ['Tech', 'Health'],
    images: ['sam.png', 'ace.jpg', 'unic.svg'],
    createdOn: new Date(),
  },
  {
    id: 5,
    organizer: 'FrontStack',
    topic: 'UI pixel perfection',
    happeningOn: '1/3/18',
    location: 'EPIC Tower, Illupeju',
    Tags: ['Tech', 'Epic'],
    images: ['shalvah.png', 'this.jpg'],
    createdOn: new Date(),
  },
  {
    id: 6,
    organizer: 'GDG',
    topic: 'Becoming a GDE',
    happeningOn: '11/11/19',
    location: 'Tech Zone Park, Lagos',
    Tags: ['Tech', 'Expert', 'google'],
    images: ['aniedi.png', 'sundar.jpg'],
    createdOn: new Date(),
  },
];

export default dummyMeetup;
